// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDivW9JKWH1VCKHPuNjTOrByRgh3KJZZiM',
    appId: '1:1031615933896:web:f03af2446db58d385ce4fd',
    messagingSenderId: '1031615933896',
    projectId: 'ptook01',
    authDomain: 'ptook01.firebaseapp.com',
    storageBucket: 'ptook01.firebasestorage.app',
    databaseURL: 'https://ptook01-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2_c49RBS9pWFvn9tSXMrrvj8QGIqu6qc',
    appId: '1:1031615933896:android:c19ed7734f16cb695ce4fd',
    messagingSenderId: '1031615933896',
    projectId: 'ptook01',
    storageBucket: 'ptook01.firebasestorage.app',
    databaseURL: 'https://ptook01-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD04xlrkH9dQupB-nbj44G1ueqblEF-o58',
    appId: '1:1031615933896:ios:fd33ab8d1c02fac95ce4fd',
    messagingSenderId: '1031615933896',
    projectId: 'ptook01',
    storageBucket: 'ptook01.firebasestorage.app',
    iosBundleId: 'com.example.ptook',
    databaseURL: 'https://ptook01-default-rtdb.firebaseio.com',
  );

}